export const qrForm = [
    { name: "RC Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=rc_norm&form_key=", type: "rc_norm" },
    { name: "CE Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=ce_norm&form_key=", type: "ce_norm" },
    { name: "CE Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=ce_work&form_key=", type: "ce_work" },
    { name: "ME Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=me_norm&form_key=", type: "me_norm" },
    { name: "ME Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=me_work&form_key=", type: "me_work" },
    { name: "ME Life Tour", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=me_life&form_key=", type: "me_life" },
    { name: "PEMCE Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=pemce_norm&form_key=", type: "pemce_norm" },
    { name: "PEMCE Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=pemce_work&form_key=", type: "pemce_work" },
    { name: "EE Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=ee_norm&form_key=", type: "ee_norm" },
    { name: "EE Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=ee_work&form_key=", type: "ee_work" },
    { name: "ENE Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=ene_norm&form_key=", type: "ene_norm" },
    { name: "ENE Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=ene_work&form_key=", type: "ene_work" },
    { name: "TME Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=tme_norm&form_key=", type: "tme_norm" },
    { name: "TME Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=tme_work&form_key=", type: "tme_work" },
    { name: "ENV Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=env_norm&form_key=", type: "env_norm" },
    { name: "ENV Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=env_work&form_key=", type: "env_work" },
    { name: "CPE Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=cpe_norm&form_key=", type: "cpe_norm" },
    { name: "CPE Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=cpe_work&form_key=", type: "cpe_work" },
    { name: "INC Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=inc_norm&form_key=", type: "inc_norm" },
    { name: "INC Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=inc_work&form_key=", type: "inc_work" },
    { name: "CHE Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=che_norm&form_key=", type: "che_norm" },
    { name: "CHE Workshop", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=che_work&form_key=", type: "che_work" },
    { name: "Central Normal", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=central_norm&form_key=", type: "central_norm" },
    { name: "Central Question", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=central_question&form_key=", type: "central_question" },
    { name: "Central Innovation", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=central_innovation&form_key=", type: "central_innovation" },
    { name: "Central Hackathon", link: "https://openhouse-api-922np.ondigitalocean.app/form?type=central_hackathon&form_key=", type: "central_hackathon" },
]